//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingSystemTests {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradingSystemTests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 17.11.1995;9,67000008
        ///20.11.1995;9,52299976
        ///21.11.1995;9,40799999
        ///22.11.1995;9,56099987
        ///23.11.1995;9,65100002
        ///24.11.1995;9,84200001
        ///27.11.1995;9,89299965
        ///28.11.1995;9,81000042
        ///29.11.1995;9,79800034
        ///30.11.1995;10,06000042
        ///01.12.1995;10,08500004
        ///04.12.1995;9,92500019
        ///05.12.1995;9,86200047
        ///06.12.1995;9,71500015
        ///07.12.1995;9,81700039
        ///08.12.1995;9,8039999
        ///11.12.1995;9,625
        ///12.12.1995;9,68299961
        ///13.12.1995;9,66300011
        ///14.12.1995;9,54800034
        ///15.12.1995;9,34500027
        ///18.12.1995;9,01200008
        ///19.12.1995 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AdidasHistory {
            get {
                return ResourceManager.GetString("AdidasHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 17.11.1995;9,67000008
        ///20.11.1995;9,52299976
        ///21.11.1995;9,40799999
        ///22.11.1995;9,56099987
        ///23.11.1995;9,65100002
        ///24.11.1995;9,84200001
        ///27.11.1995;9,89299965
        ///28.11.1995;9,81000042
        ///29.11.1995;9,79800034
        ///30.11.1995;10,06000042
        ///01.12.1995;10,08500004
        ///04.12.1995;9,92500019
        ///05.12.1995;9,86200047
        ///06.12.1995;9,71500015
        ///07.12.1995;9,81700039
        ///08.12.1995;9,8039999
        ///11.12.1995;9,625
        ///12.12.1995;9,68299961
        ///13.12.1995;9,66300011
        ///14.12.1995;9,54800034
        ///15.12.1995;9,34500027
        ///18.12.1995;9,01200008
        ///19.12.1995 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AdidasHistoryMissingItems {
            get {
                return ResourceManager.GetString("AdidasHistoryMissingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DateTime;SecurityId;Shares;EffectiveAmountEur;Type;Cancelled;TargetWeight
        ///01.10.2017;1;30;30000;1;0;0.10;
        ///01.10.2017;2;30;30000;1;0;0.10;
        ///01.10.2017;3;30;30000;1;0;0.10;
        ///01.10.2017;4;30;30000;1;0;0.10;
        ///01.10.2017;5;30;30000;1;0;0.10;
        ///01.10.2017;6;30;30000;1;0;0.10;
        ///01.10.2017;7;30;30000;1;0;0.10;
        ///01.10.2017;8;30;30000;1;0;0.10;
        ///01.10.2017;9;30;30000;1;0;0.10;
        ///01.10.2017;10;30;30000;1;0;0.10;
        ///
        ///04.10.2017;10;-15;-12000;3;0;0.05;
        ///04.10.2017;9;-15;-10000;3;0;0.05;
        ///04.10.2017;11;10;30000;1;0;0.10;        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CashTest {
            get {
                return ResourceManager.GetString("CashTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 26.10.1998;67,874
        ///27.10.1998;67,158
        ///28.10.1998;65,445
        ///29.10.1998;64,934
        ///30.10.1998;66,468
        ///02.11.1998;68,59
        ///03.11.1998;66,724
        ///04.11.1998;69,28
        ///05.11.1998;70,712
        ///06.11.1998;71,274
        ///09.11.1998;68,718
        ///10.11.1998;65,701
        ///11.11.1998;66,212
        ///12.11.1998;67,388
        ///13.11.1998;67,235
        ///16.11.1998;71,939
        ///17.11.1998;71,172
        ///18.11.1998;71,99
        ///19.11.1998;75,773
        ///20.11.1998;78,483
        ///23.11.1998;80,912
        ///24.11.1998;80,043
        ///25.11.1998;78,228
        ///26.11.1998;81,398
        ///27.11.1998;82,216
        ///30.11.1998;81,449
        ///01.12.1998;77,819
        ///02 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Daimler {
            get {
                return ResourceManager.GetString("Daimler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] EuroStoxx50Member {
            get {
                object obj = ResourceManager.GetObject("EuroStoxx50Member", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DateTime;SecurityId;Shares;AmountEur;Type;Cancelled;TargetWeight
        ///01.10.2017;1;30;30000;1;0;0.10;
        ///01.10.2017;2;30;30000;1;0;0.10;
        ///01.10.2017;3;30;30000;1;0;0.10;
        ///01.10.2017;4;30;30000;1;0;0.10;
        ///01.10.2017;5;30;30000;1;0;0.10;
        ///01.10.2017;6;30;30000;1;0;0.10;
        ///01.10.2017;7;30;30000;1;0;0.10;
        ///01.10.2017;8;30;30000;1;0;0.10;
        ///01.10.2017;9;30;30000;1;0;0.10;
        ///01.10.2017;10;30;30000;1;0;0.10;
        ///
        ///04.10.2017;10;-15;12000;3;0;0.05;
        ///04.10.2017;9;-15;10000;3;0;0.05;
        ///04.10.2017;11;10;30000;1;0;0.10;
        ///
        ///
        /// ähnelt.
        /// </summary>
        internal static string GetCurrentTransactionsTest {
            get {
                return ResourceManager.GetString("GetCurrentTransactionsTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DateTime;SecurityId;Shares;AmountEur;Type;Cancelled;TargetWeight
        ///01.10.2017;1;30;30000;1;0;0.10;
        ///01.10.2017;2;30;30000;1;0;0.10;
        ///01.10.2017;3;30;30000;1;0;0.10;
        ///01.10.2017;4;30;30000;1;0;0.10;
        ///01.10.2017;5;30;30000;1;0;0.10;
        ///01.10.2017;6;30;30000;1;0;0.10;
        ///01.10.2017;7;30;30000;1;0;0.10;
        ///01.10.2017;8;30;30000;1;0;0.10;
        ///01.10.2017;9;30;30000;1;0;0.10;
        ///01.10.2017;10;30;30000;1;0;0.10;
        ///
        ///04.10.2017;10;-15;12000;3;0;0.05;
        ///04.10.2017;9;-15;10000;3;0;0.05;
        ///04.10.2017;11;10;30000;1;0;0.10;
        ///
        ///08.10.20 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GetTransactionTest {
            get {
                return ResourceManager.GetString("GetTransactionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TransactionDateTime;SecurityId;Shares;AmountEur;TransactionType;Cancelled;TargetWeight;EffectiveWeight
        ///11.10.2016 00:00:00;8;125;10000.0;1;0;0.1;0.0995
        ///11.10.2016 00:00:00;16;487;10000.0;1;0;0.1;0.0999
        ///11.10.2016 00:00:00;13;60;10000.0;1;0;0.1;0.0985
        ///11.10.2016 00:00:00;9;205;10000.0;1;0;0.1;0.0995
        ///11.10.2016 00:00:00;14;890;10000.0;1;0;0.1;0.1000
        ///11.10.2016 00:00:00;19;890;10000.0;1;0;0.1;0.1000
        ///11.10.2016 00:00:00;2;95;10000.0;1;0;0.1;0.0994
        ///11.10.2016 00:00:00;12;155;10000.0;1;0;0.1;0.0995
        ///11.10 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string SetIntialTransactionsTest {
            get {
                return ResourceManager.GetString("SetIntialTransactionsTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DateTime;SecurityId;Shares;AmountEur;Type;Cancelled;TargetWeight
        ///01.10.2017;1;30;30000;1;0;0.10;
        ///01.10.2017;2;30;30000;1;0;0.10;
        ///01.10.2017;3;30;30000;1;0;0.10;
        ///01.10.2017;4;30;30000;1;0;0.10;
        ///01.10.2017;5;30;30000;1;0;0.10;
        ///01.10.2017;6;30;30000;1;0;0.10;
        ///01.10.2017;7;30;30000;1;0;0.10;
        ///01.10.2017;8;30;30000;1;0;0.10;
        ///01.10.2017;9;30;30000;1;0;0.10;
        ///01.10.2017;10;30;30000;1;0;0.10;
        ///
        ///
        ///04.10.2017;10;-15;12000;10;2;0;0.5;
        ///04.10.2017;9;-15;10000;9;2;0;0.5;
        ///04.10.2017;11;10;30000;1;0;0.10;
        ///
        ///
        ///0 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string TransactionsHistoryTest {
            get {
                return ResourceManager.GetString("TransactionsHistoryTest", resourceCulture);
            }
        }
    }
}
